# Base image https://hub.docker.com/u/rocker
FROM rocker/shiny:3.6.3

## system libraries of general use
RUN apt-get update && apt-get install -y \
    sudo \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev 
	
## install r packages
RUN R -e "install.packages('dplyr', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('shiny', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('shinydashboard', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('COVID19', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('remotes', repos='http://cran.rstudio.com/')"
RUN R -e "remotes::install_github('nik01010/dashboardthemes')"


## copy the app to the image
COPY app.R /srv/shiny-server/
COPY theme_diy.R /srv/shiny-server/


## select port
EXPOSE 3838

#allow permission
RUN sudo chown -R shiny:shiny /srv/shiny-server/
COPY shiny-server.sh /usr/bin/shiny-server.sh

## run app
CMD [“/usr/bin/shiny-server.sh”]



